#! /usr/bin/perl -w

#--------------------------------------------------------------------------
# $HeadURL: file:///var/lib/svn/scripts/alldl $
#--------------------------------------------------------------------------
# $Revision: 178 $
# $Date: 2006-03-06 11:10:48 -0500 (Mon, 06 Mar 2006) $
# $Author: dmorelli $
#
# Download an entire album of music from allofmp3 by parsing the download
# HTML page containing them.
#--------------------------------------------------------------------------

use strict;


# Path to HTML document from allofmp3 with URLs
my $htmlPath = shift;
my %urlHash;

# Extract the URLs from the file, there will be dupes, get rid of them
open HTML, "$htmlPath" or die "Can't open $htmlPath: $!\n";
while (<HTML>) {
   if (m[(http.*://.*\.(?:ogg|mp3))]) {
      $urlHash{$1}++;
   }
}
close HTML;

# Use wget to download the files from above
for (keys %urlHash) {
   system qq[wget "$_"];
}
