#! /bin/bash

# A script to start Amnesia: The Dark Descent

# Put this script somewhere like this, in your path,
# and make sure it's executable:
#    /usr/local/bin/amnesia


# Change this to the installation dir
gamedir=/usr/local/games/Amnesia


basename=$(basename $0)

function usage {
   cat <<USAGE
$basename - start Amnesia: The Dark Descent

usage:
   $basename [OPTIONS]

options:
   -c, --conf  Run configuation tool first (Launcher.bin
               instead of Amnesia.bin)
   -h, --help  This help information

2010-09-10  Dino Morelli <dino@ui3.info>

USAGE

   exit 0
}


function launch {
   binary=$1

   killall xscreensaver
   cd $gamedir
   $binary
   xscreensaver -no-splash &
   exit 0
}


# arg parsing
getoptResults=`getopt -o ch --long conf,help -n $basename -- "$@"`

# getopt arg parsing failed?
if [ $? != 0 ] ; then usage ; fi

# Note the quotes around `$VAR': they are essential!
eval set -- "$getoptResults"

while true ; do
   case "$1" in
      -c|--conf) launch ./Launcher.bin ;;
      -h|--help) usage ;;
      --) shift ; break ;;
   esac
done

launch ./Amnesia.bin
