#! /bin/bash

# Script to perform the common-case data DVD burning. Argument should be a
# directory at a minimum. Any other growisofs or mkisofs args are
# good here.

device=/dev/scd0
prefix="growisofs -Z $device -r -J"

case "$1" in
   "" | "-h" | "--help")
      echo "command: $prefix [ADDL ARGS] DIR"
      echo "useful args:"
      echo "  -joliet-long instead of -J"
      echo "  -speed=1, 2 or 4 instead of default"
      exit 1
      ;;
esac

$prefix $*
