#! /usr/bin/env bash

# Script to perform the common-case data CD burning. Argument should be a
# ISO image file at a minimum. Any other cdrecord/wodim args are good here.

device=/dev/sr0

prefix="cdrecord driveropts=burnfree -tao dev=$device -v -eject"

case "$1" in
   "" | "-h" | "--help")
      echo "command: $prefix [ADDL ARGS] ISOFILE"
      echo "useful args:"
      echo "  speed=1, 4, 8, etc instead of default"
      exit 1
      ;;
esac

$prefix $*
