#! /bin/bash

# Script to perform the common-case data CD burning. Argument should be a
# ISO image file at a minimum. Any other cdrecord/wodim args are good here.

device=/dev/scd0
prefix="cdrecord driveropts=burnfree -tao dev=$device"

case "$1" in
   "" | "-h" | "--help")
      echo "command: $prefix [ADDL ARGS] DIR"
      echo "useful args:"
      echo "  -v for verbose output"
      echo "  speed=1, 4, 8, etc instead of default"
      echo "  -eject to eject media after burn"
      exit 1
      ;;
esac

$prefix $*
