#! /bin/bash

set -x

runhaskell Setup.hs clean
runhaskell Setup.hs configure --global
runhaskell Setup.hs build
runhaskell Setup.hs test
runhaskell Setup.hs haddock

set +x

echo
echo "Seems ready. You can now perform as root:"
echo "  # runhaskell install"
