#! /bin/bash

# Script to thoroughly check the contents of a CD against the directory
# it was burned from, using md5sum

md5Sums=$(mktemp --tmpdir --suffix=.md5 cdcheck-XXXX)
optMount="/media/cd"

find . -type f | xargs md5sum | tee $md5Sums

mount $optMount
pushd $optMount

md5sum -c $md5Sums || echo "FAILED, THIS DISC IS PROBABLY BAD!"

popd
umount $optMount

rm $md5Sums
