#! /bin/sh

#--------------------------------------------------------------------------
# Script to quickly check the contents of the inserted CD and then
# umount it.
#--------------------------------------------------------------------------

# Script to quickly display back the root dir of the CD in the 
# drive and then umount it.

CDDIR=/media/cd

mount $CDDIR
ls -lh $CDDIR
umount $CDDIR

