#! /usr/bin/perl -w

#--------------------------------------------------------------------------
# $HeadURL: file:///var/lib/svn/scripts/cputemp $
#--------------------------------------------------------------------------
# $Revision: 187 $
# $Date: 2006-04-19 17:25:41 -0400 (Wed, 19 Apr 2006) $
# $Author: dmorelli $
#
# Display cpu temperature
#--------------------------------------------------------------------------

use strict;


# File where the current temperature is stored
my $tempPath = '/proc/acpi/thermal_zone/THM/temperature';

# Load the contents of this file into a string
open TEMPERATURE, "$tempPath"
    or die "Can't acquire temperature from $tempPath: $!\n";
my $raw = <TEMPERATURE>;
close TEMPERATURE;

# Extract the numeric portion, temperature in Celsius
my ($celsius) = $raw =~ /\D*(\d+)\D*/;

# Convert to Fahrenheit and format for display
my $fahrenheit = $celsius * 9 / 5 + 32;

# Format for display
# This degrees symbol was a bitch to locate
print "The temperature as reported by $tempPath\n";
printf "%5.1f\260F (%2d\260C)\n", $fahrenheit, $celsius;
print scalar(localtime) . "\n";
