#! /usr/bin/perl

# This is a quick and dirty script to hack --toggle behavior into the 
# disper monitor switching utility. It's my hope that this will be 
# shortly obsoleted by new disper features.

use strict;
use warnings;


# Args that are always needed for disper

my $disperArgs = '--scaling native ';


# Use nvidia-settings to get the TwinView status

my ($twinViewStatus) = `nvidia-settings --query TwinView` =~
      /Attribute 'TwinView' \(.*\): (\d)\./;


# Configure args for disper

$disperArgs .= $twinViewStatus
   # TwinView is on (1), we need to switch to single
   ? '--single'
   # TwinView is off (0), we need to extend
   : '--extend';


# Perform the switch

system "disper $disperArgs";


# Extra fun stuff

# Screen metrics have possibly (probably?) changed, root window 
# background probably borken now.

# Reinstate my beloved root window image. I use feh for this, so:
my $rootImgSetter = "$ENV{HOME}/.fehbg";
system "eval `cat $rootImgSetter`" if -e $rootImgSetter;
