#!/bin/bash


# Find these for your system in xrandr output
laptopDisplay="LVDS-0"
extDisplay="HDMI-0"


basename=`basename $0`


function usage {
   cat <<USAGE
$basename - Change active outputs

usage:
   $basename [OPTIONS] PROFILE

options:
   -h, --help  This help info

profiles:
   laptop   Laptop display only
   ext      External monitor only
   both     Both of the above outputs, laptop on the left

USAGE

   exit 1
}


commonSwitches="--dpi 100"

case "$1" in
   laptop)  switches="--output $laptopDisplay --auto --output $extDisplay --off $commonSwitches" ;;
   ext)     switches="--output $laptopDisplay --off --output $extDisplay --auto $commonSwitches" ;;
   both)    switches="--output $laptopDisplay --auto --output $extDisplay --auto --right-of $laptopDisplay $commonSwitches" ;;
   *) usage ;;
esac


set -x
xrandr $switches
eval `cat $HOME/.fehbg`
