#! /bin/sh

#--------------------------------------------------------------------------
# Script to fix the line ending of a DOS style file to be like Unix
#--------------------------------------------------------------------------

set -u

newfile=$1
oldfile=${newfile}.old

mv $newfile $oldfile

sed -e 's///' $oldfile > $newfile

if [ -e $newfile ]
then
	rm $oldfile
fi

