#! /usr/bin/perl -w

#--------------------------------------------------------------------------
# $HeadURL: file:///var/lib/svn/scripts/examchar $
#--------------------------------------------------------------------------
# $Revision: 168 $
# $Date: 2006-01-28 11:58:22 -0500 (Sat, 28 Jan 2006) $
# $Author: dmorelli $
#
# Examine a character to get dec and hex values
#--------------------------------------------------------------------------

use strict;
use File::Basename;


my $input = shift;
my $basename = basename $0;
my $usage = <<USAGE;
$basename - Examine a character to get dec and hex values

usage
   $basename <char>
   $basename 0x<hex>
   $basename d<dec>
USAGE

$input || die "$usage\n";

my ($char, $dec, $hex);


SWITCH: {
   # It's hex
   $input =~ /^0x/ && do {
      $hex = $input;
      $dec = hex $hex;
      $char = chr $dec;
      last SWITCH;
   };

   # It's decimal
   $input =~ /^d(\d{1,3})/ && do {
      $dec = $1;
      $char = chr $dec;
      $hex = sprintf "0x%lx", $dec;
      last SWITCH;
   };

   # Everything else, probably char
   1 && do {
      $char = $input;
      $dec = ord $char;
      $hex = sprintf "0x%lx", $dec;
      last SWITCH;
   };
}

printf "char: %s  dec: %i  hex: %s\n", $char, $dec, $hex;
