#! /bin/bash


# 5 minutes
defaultDelay=300


# Send messages to stdout tagged as originating from this script.
msg () {
   echo "$(basename $0)  $(date): $1"
}


# It all starts here

# Use default delay time if none supplied.
delay=${1:-$defaultDelay}

msg "Started"

while [ 1 ]  # Run forever
do
   if xset q | grep -q "DPMS is Disabled"
   then
      msg "Re-enabling dpms now"
      xset +dpms
   fi

   #msg "sleeping"
   sleep $delay
done
