#! /bin/bash

# fix keyboard mapping using Xkb


# setxkbmap is a more civilized way to do this but some keys can't be mapped easily with it...
# setxkbmap -option ctrl:swapcaps -option keypad:pointerkeys -option compose:sclk

# ...in those cases, a custom .Xkeymap file can be used
test -f ~/.Xkeymap && xkbcomp -w 3 ~/.Xkeymap $DISPLAY
