#! /bin/sh

#--------------------------------------------------------------------------
# $HeadURL: file:///var/lib/svn/scripts/fr $
#--------------------------------------------------------------------------
# $Revision: 192 $
# $Date: 2006-08-09 10:18:46 -0400 (Wed, 09 Aug 2006) $
# $Author: dmorelli $
#
# Restart fetchmail daemon (when run for an individual user)
#--------------------------------------------------------------------------


fetchmail -q
sleep 1
fetchmail
echo -n "Newly started fetchmail pid: "
head -n 1 ~/.fetchmail.pid
