#!/bin/bash

# Perform a test build on a Haskell package, to be done between cabal 
# sdist and Hackage upload

if [ ! -f "$1" ]
then
   echo "usage: $0 PACKAGE_ARCHIVE"
   exit 1
fi

set -e

sandboxConfFile=$(pwd)/cabal.sandbox.config

# Get absolute path to the passed Haskell package
package=$(readlink -m $1)

# Unpack it in /tmp
cd /tmp
tar xzf $package

# Perform the full build, test, the works
buildDir=$(basename $package .tar.gz)
cd $buildDir
[ -f "$sandboxConfFile" ] && cp $sandboxConfFile .
cabal configure --enable-tests
cabal build
cabal test
cabal haddock

# Clean up that mess
cd ..
rm -rf $buildDir

# If we got here, this was successful
echo "Package $buildDir builds successfully!"
