#! /bin/sh

#--------------------------------------------------------------------------
# $HeadURL: file:///var/lib/svn/scripts/jing $
#--------------------------------------------------------------------------
# $Revision: 157 $
# $Date: 2005-09-12 15:41:03 -0400 (Mon, 12 Sep 2005) $
# $Author: dmorelli $
#
# Script to invoke the command-line Jing RelaxNG 
# schema validator for XML
#
# Jing home page: http://www.thaiopensource.com/relaxng/jing.html
#--------------------------------------------------------------------------

java -classpath ~/lib/java/jing.jar com.thaiopensource.relaxng.util.Driver $1 $2 $3 $4 $5 $6 $7 $8 $9

