#! /bin/sh

#--------------------------------------------------------------------------
# Do some meaningless work to keep a connection alive
#--------------------------------------------------------------------------


while echo `hostname;date`; do sleep 120; done
