#! /bin/sh

#--------------------------------------------------------------------------
# $HeadURL: file:///var/lib/svn/scripts/keepalive $
#--------------------------------------------------------------------------
# $Revision: 177 $
# $Date: 2006-03-06 11:03:48 -0500 (Mon, 06 Mar 2006) $
# $Author: dmorelli $
#
# Do some meaningless work to keep a connection alive
#--------------------------------------------------------------------------


while echo `hostname;date`; do sleep 120; done
