#! /bin/bash

# Process /SOMEDIR/FILE.md or .markdown into
# /SOMEDIR/FILE.html using Pandoc

# If you just want to write HTML to stdout:
#  $ pandoc -s -t html MDPATH


MDPATH=$1
MDFILE=$(basename $MDPATH)
HTMLPATH="$(dirname $MDPATH)/${MDFILE%.*}.html"

pandoc -s -o $HTMLPATH $MDPATH
