#! /bin/bash

# Add files to this list as needed
files=(
   .bash_profile
   .bashrc
   .cabal/config
   .darcs/defaults
   .vimrc
)

archive="carepkg-$USER-$HOSTNAME.tar"

cd $HOME
rm -v $archive
tar cvf $archive ${files[*]} $*

echo
echo "File $archive created. Add more files like this:"
echo "   $ tar uvf $archive FILE..."
echo ""
echo "   Suggested files that may be helpful:"
echo "      .ssh/id_rsa.pub"
