#! /bin/bash

# This is the default set of files to be archived into the care package
# Add to this list as needed, these are relative to ~
files=(
   .bash_profile
   .bashrc
   .cabal/config
   .darcs/defaults
   .vimrc
)

archive="carepkg-$HOSTNAME-$USER.tar"

cd $HOME
rm -v $archive
tar cvf $archive ${files[*]} $*

cat << INFO

File $HOME/$archive created

Add more files by running this script again:
   $ mkcarepkg FILE1 FILE2 ...

Or add to existing tar like this:
   $ tar uvf $archive FILE...

Some additional files that may be helpful:
   .gitconfig
   .profile
   .ssh/id_rsa.pub
INFO
