#! /bin/bash

# Mount an iso image to /mnt
# Must be run with root permissions

set -u
set -e

isoFile="$1"
mountPoint="/mnt"

mount "$isoFile" -r -t iso9660 -o loop $mountPoint

echo "$isoFile mounted at $mountPoint"
echo "To unmount:"
echo "  # umount /mnt"
