#! /bin/bash


basename=$(basename $0)

function usage {
   cat <<USAGE
$basename - Mount mobile device using sshfs

usage:
   $basename HOST:PATH/TO/MOUNT/ /LOCAL/MOUNT/POINT [PORT]

Common values for PATH/TO/MOUNT/ on modern Android:
   /storage/sdcard0/
   /storage/extSdCard/

Also, this script does several handy things:

1) The sshfs sometimes repeatedly fails, so it's wrapped in an until
   statement and keeps trying
2) If you forget the trailing slash on the PATH/TO/MOUNT/ above,
   it fails. So one is added for you just in case.
3) Defaults to port 2222, (default for SSH Droid) so you don't have
   to type it

USAGE

   exit 1
}


# First two arguments are required, show usage if they're missing
[ -z "$2" ] && usage

# Default port if missing
port=${3:-2222}

until sshfs root@$1/ $2 -p $port ; do sleep 1 ; done

cat <<FOOTER

Make sure you unmount later:
  $ fusermount -u $mntpt
FOOTER
