#! /usr/pkg/bin/perl -w

#--------------------------------------------------------------------------
# $HeadURL: file:///var/lib/svn/scripts/mt2blos $
#--------------------------------------------------------------------------
# $Revision: 157 $
# $Date: 2005-09-12 15:41:03 -0400 (Mon, 12 Sep 2005) $
# $Author: dmorelli $
#
# Make Movable Type exported data into Blosxom data files.
#--------------------------------------------------------------------------


$untitledIndex = 0;


#-------------------------------------------------------------------------
sub savePost()
{
	#my $dataDir = "data/";
	my $dataDir = "/arpa/ag/d/dmorelli/var/local/hobgoblinData/";

	my $basename = constructName();
	my $postPath = $dataDir . $basename . ".txt";
	my $datePath = $dataDir . $basename . ".timestamp";

	open POSTFILE, ">$postPath" or die "Can't open $postPath: $!\n";

	print POSTFILE "$title\n";
	print POSTFILE "$body";
	# Keep some stuff in comments.
	#print POSTFILE "<!-- ";
	#print POSTFILE "postDate: $date";
	#print POSTFILE " -->";
	#print POSTFILE "<!-- comment -->";

	close POSTFILE;

	# Fix the file modified date.
	$date =~ m<([0-9]{2})/([0-9]{2})/([0-9]{2})([0-9]{2}) ([0-9]{2}):([0-9]{2}):([0-9]{2}) (A|P)M>;
	my $CC = $3;
	my $YY = $4;
	my $MM = $1;
	my $DD = $2;
	my $hh = $5;
	my $mm = $6;
	my $SS = $7;
	my $timestamp = "$CC$YY$MM$DD$hh$mm.$SS";
	if(($8 eq "P") && ($hh < 12)) { $hh += 12; }
	qx|touch -t $timestamp $postPath|;

	open TIMESTAMPFILE, ">$datePath" or die "Can't open $datePath: $!\n";
	print TIMESTAMPFILE "$timestamp";
	close TIMESTAMPFILE;
}  # savePost


#-------------------------------------------------------------------------
sub constructName()
{
	my $name;

	if($title eq "")
	{
		$title = "--";
		$name = sprintf("untitled%02d", ++$untitledIndex);
	}
	else
	{
		$name = $title;
		$name =~ s/^(.)/\L$1/;
		$name =~ s/[,.!']//g;
		$name =~ s/[-]//g;
		$name =~ s/[ ](.)/\U$1/g;
	}

	return $name;
}  # sub constructName


#-------------------------------------------------------------------------
$srcPath = "hobgoblinBackup.txt";
open srcPath or die "Can't open file $srcPath: $!\n";

$done = 0;
$authorCount = 0;
while (!$done)
{
	$line = readline srcPath;
	if(!$line)
	{
		$done = 1;
		savePost();
	}
	else
	{
		SWITCH:
		{
			$line =~ m/^TITLE: (.*)$/ && do { $title = $1; last SWITCH; };
			$line =~ m/^DATE: (.*)$/ && do { $date = $1; last SWITCH; };
			$line =~ m/^BODY:.*$/ && do
			{
				$body = "";
				$gotBody = 0;
				while(!$gotBody)
				{
					$line = readline srcPath;
					if($line =~ m/^-----.*/) { $gotBody = 1; }
					else { $body .= $line; }
				}
			};
			$line =~ m/^AUTHOR: .*$/ && do
			{
				if(++$authorCount > 1) { savePost() }
			};
		}
	}
}

close srcPath;
