#! /bin/sh

#--------------------------------------------------------------------------
# $HeadURL: file:///var/lib/svn/scripts/nassh $
#--------------------------------------------------------------------------
# $Revision: 186 $
# $Date: 2006-04-07 08:23:57 -0400 (Fri, 07 Apr 2006) $
# $Author: dmorelli $
#
# Connect to Network Appliance via ssh
#--------------------------------------------------------------------------


COCONUT_IP=10.61.25.28
NETAPP_GATEWAY_IP=198.95.225.6

echo "On the other side, coconut's IP is: $COCONUT_IP"
echo "Connecting to NetApp now..."

ssh -l morelli -p 48558 -i ${HOME}/.ssh/identity-na $NETAPP_GATEWAY_IP
