#!/bin/sh

#--------------------------------------------------------------------------
# ntpdate cron nightly, this is from:
# http://www.debian.org/doc/manuals/system-administrator/ch-sysadmin-time.html
#--------------------------------------------------------------------------


PATH=/sbin:/bin

test -f /usr/sbin/ntpdate || exit 0

if test -f /etc/default/ntpdate ; then
. /etc/default/ntpdate
else
NTPSERVERS="pool.ntp.org"
fi

test -n "$NTPSERVERS" || exit 0

# Not using -b which would step clock rather than slew. -b is for
# calling at system boot
/usr/sbin/ntpdate -s $NTPOPTIONS $NTPSERVERS

exit 0
