#! /bin/bash

#photoSrcPath=/media/sdreader
photoSrcPath=/media/panasonic_DMC-FX07

incomingPath=~/pictures/incoming

echo
pushd $incomingPath

echo
echo "Mounting $photoSrcPath"
mount $photoSrcPath

echo
echo "Copying files..."
find $photoSrcPath -regex ".*\.jpg" -exec cp -v {} "$incomingPath/" \;

echo
echo "Unmounting $photoSrcPath"
umount $photoSrcPath

echo
echo "Changing permissions to NOT executable"
chmod -v a-x *.jpg

echo
echo "Repairing rotation information where necessary"
jhead -autorot *.jpg

#echo
#echo "Linking photos properly with the rest"
#photoname ~/pictures/photos *.jpg

#echo
#echo "If all went well, you may now wish to remove the hard links that"
#echo "remain in this directory."

echo
popd
