#! /bin/sh

sdCardPath=/media/sdreader
incomingPath=~/pictures/incoming

echo
pushd $incomingPath

echo
echo "Mounting SD card on $sdCardPath"
mount $sdCardPath

echo
echo "Copying files from SD media..."
find $sdCardPath -regex ".*\.jpg" -exec cp -v {} "$incomingPath/" \;

echo
echo "Unmounting SD card on $sdCardPath"
umount $sdCardPath

echo
echo "Changing permissions to NOT executable"
chmod -v a-x *.jpg

echo
echo "Repairing rotation information where necessary"
jhead -autorot *.jpg

echo
echo "Linking photos properly with the rest"
photoname ~/pictures/photos *.jpg

echo
echo "If all went well, you may now wish to remove the hard links that"
echo "remain in this directory."

echo
popd
