#! /bin/sh

#--------------------------------------------------------------------------
# $HeadURL: file:///var/lib/svn/scripts/sdmusic $
#--------------------------------------------------------------------------
# $Revision: 176 $
# $Date: 2006-02-28 13:44:07 -0500 (Tue, 28 Feb 2006) $
# $Author: dmorelli $
#
# Replace all music on the SD card
#--------------------------------------------------------------------------


mount /mnt/sd/

rm -fv /mnt/sd/Music/*

/usr/local/bin/mkplaylist -e ~/doc/pdaExclude.m3u /mnt/sd/Music/

umount /mnt/sd

if [ $? != 0 ]
then
   echo "Problem with unmount!"
else
   echo "SD card is now unmounted and can be removed"
fi
