#! /usr/bin/perl -w

#--------------------------------------------------------------------------
# Convert seconds into MM:SS notation
#--------------------------------------------------------------------------

use strict;
use POSIX qw(floor);


my $dec = shift() / 60;
my $m = floor $dec;
my $s = ($dec - $m) * 60;
printf "%02i:%02i\n", $m, $s;
