#! /bin/bash

basename=$(basename "$0")
defaultSubject="no subject"

optFrom="${USER}@${HOSTNAME}.localdomain"
optTo="$USER"
optHelp=false

usage=$(cat <<USAGE
Send a simple email

usage:
   $basename [OPTIONS] [SUBJECT] BODY

options:
  -f, --from EMAIL  Email sender, default "$optFrom"
  -t, --to EMAIL    Email recipient, default "$optTo"
  -h, --help        This help info

If omitted, SUBJECT defaults to "$defaultSubject"

Note that some recipient email addresses will reject the default sender this
script will produce. In those cases, try a valid email address instead with the
--from switch.

v1.2  2021-07-30  Dino Morelli <dino@ui3.info>

USAGE
)


warn () {
  echo "$basename:" "$@" >&2
}


die () {
  rc="$1"
  shift
  warn "$@"
  exit "$rc"
}


# arg parsing

getoptResults=$(getopt -o f:t:h --long from:,to:,help -n "$basename" -- "$@") \
  || die 1 "$usage"

# Note the quotes around "$getoptResults": they are essential!
eval set -- "$getoptResults"

while true ; do
  case "$1" in
    -f|--from) optFrom="$2"; shift 2;;
    -t|--to) optTo="$2"; shift 2;;
    -h|--help) optHelp=true; shift;;
    --) shift; break;;
  esac
done

$optHelp && die 0 "$usage"

case "$#" in
  2) subject="$1"; body="$2";;
  1) subject="$defaultSubject"; body="$1";;
  *) warn "Can't continue, incorrect number of arguments"; die 1 "$usage";;
esac

/usr/sbin/sendmail -ti <<MESSAGE
From: $optFrom
To: $optTo
Subject: $subject
Content-Type: text/plain; charset=utf-8
Content-Disposition: inline

$body
MESSAGE
