#! /bin/bash

basename=$(basename "$0")
defaultSubject="no subject"

unset optFrom
optTo="$USER"
optHelp=false
optDebug=""

usage=$(cat <<USAGE
Send a simple email

usage:
   $basename [OPTIONS] [SUBJECT] BODY

options:
  -f, --from EMAIL  Email sender, defaults to sendmail's configuration
  -t, --to EMAIL    Email recipient, default "$optTo"
  -d, --debug       Pass --debug to sendmail
  -h, --help        This help info

If omitted, SUBJECT defaults to "$defaultSubject"

If you have /etc/aliases set up, the default --to will send to those addresses
that map to the user name.

Note that some recipient email addresses will reject the default sender this
script will produce, it may be dependent on the sendmail configuration. In
those cases, try a valid email address for the account instead with the --from
switch.

v1.3  2023-04-28  Dino Morelli <dino@ui3.info>

USAGE
)


warn () {
  echo "$basename:" "$@" >&2
}


die () {
  rc="$1"
  shift
  warn "$@"
  exit "$rc"
}


# arg parsing

getoptResults=$(getopt -o f:t:dh --long from:,to:,debug,help -n "$basename" -- "$@") \
  || die 1 "$usage"

# Note the quotes around "$getoptResults": they are essential!
eval set -- "$getoptResults"

while true ; do
  case "$1" in
    -t|--to) optTo="$2"; shift 2;;
    -f|--from) optFrom="$2"; shift 2;;
    -d|--debug) optDebug="--debug"; shift;;
    -h|--help) optHelp=true; shift;;
    --) shift; break;;
  esac
done

# Because of weird trailing newline stuff, we need to construct the From and To
# headers together if we're specifying a From at all.
if [[ -z ${optFrom+x} ]]
  then optFromTo=$(printf "To: %s" "$optTo")
  else optFromTo=$(printf "From: %s\nTo: %s" "$optFrom" "$optTo")
fi

$optHelp && die 0 "$usage"

case "$#" in
  2) subject="$1"; body="$2";;
  1) subject="$defaultSubject"; body="$1";;
  *) warn "Can't continue, incorrect number of arguments"; die 1 "$usage";;
esac

/usr/sbin/sendmail "$optDebug" -ti <<MESSAGE
${optFromTo}
Subject: $subject
Content-Type: text/plain; charset=utf-8
Content-Disposition: inline

$body
MESSAGE
