#! /bin/bash

# Specialized switches for tree for development directories which often contain
# a lot of noisy build artifacts.


# Add directories to this list
ignoreDirs=(
  '_cache'          # Hakyll cache directory
  '_darcs'          # darcs source control
  '.git'            # git source control
  'node_modules'    # JavaScript: npm download directories
  'project/target'  # Scala: sbt build artifacts
  'target'          # Scala: sbt build artifacts
)

# Combine the dirs together delimited with | chars
ignoreArg=$(printf "|%s" "${ignoreDirs[@]}")
# Remove the first "dangling" | character
ignoreArg=${ignoreArg:1}

# Note: Using -a so we get all dotfiles and directories, BUT placing the -I
# ignore switch after means some things get filtered out (like .git from our
# list above)
eval "tree -a -I \"$ignoreArg\" $*"
