#! /bin/bash

# Specialized switches for tree for development directories which often contain
# a lot of noisy build artifacts.


# Add directories to this list
ignoreDirs=(
  '.idea'           # IntelliJ
  '*cache*'         # We never want to see caches of any kind
  '.import'         # Godot

  # Haskell
  'dist-newstyle'   # cabal build artifacts directory
  '.stack-work'     # stack build artifacts directory

  # JavaScript, ECMAScript, TypeScript
  'node_modules'    # npm download directories

  # Maven, sbt, JVM, Java and Scala
  'project/target'  # maven/sbt build artifacts
  'target'          # maven/sbt build artifacts

  # Python
  '.venv'           # Conventional Python virtual env directory

  # Source control
  '_darcs'          # darcs
  '.git'            # git
)

# Combine the dirs together delimited with | chars
ignoreArg=$(printf "|%s" "${ignoreDirs[@]}")
# Remove the first "dangling" | character
ignoreArg=${ignoreArg:1}

# Note: Using -a so we get all dotfiles and directories, BUT placing the -I
# ignore switch after means some things get filtered out (like .git from our
# list above)
# shellcheck disable=SC2048 disable=SC2086
tree -a -I "$ignoreArg" $*
