#! /bin/sh

#--------------------------------------------------------------------------
# $HeadURL$
#--------------------------------------------------------------------------
# $Revision$
# $Date$
# $Author$
#
# Move everything in a Subversion repository trunk dir to the parent of
# trunk.
#--------------------------------------------------------------------------


# Start in the project's top-level dir
if [ ! -e trunk ] then
    echo "No trunk directory. Are you sure you're in the top-level?"
    exit 1
fi

# Temp file to store the list of files/dirs to move
TMPFILE=`mktemp -t uptrunk.XXXXXX` || exit 1

# List of all files and dirs excluding .svn dirs, top level only
pushd trunk
find . -maxdepth 1 -not -regex '.*\.svn.*' -not -regex '\.' > $TMPFILE

# For each of the paths from above, move from trunk to top-level
popd
for F in `cat $TMPFILE`; do svn mv trunk/$F $F ; done

# Commit these changes
MSG='Removed trunk dir'
cat $TMPFILE | xargs svn ci -m "Moved from trunk to project top-level"
svn ci -m "$MSG" trunk/

# Get rid of the trunk dir too
svn rm trunk
svn up
svn ci -m "$MSG" trunk

# Clean up the temp file
rm $TMPFILE
