#! /usr/bin/env bash


basename=$(basename "$0")

vpnservice="$VPNCTL_SERVICE"


usage=$(cat <<USAGE
Control the vpn service

usage:
  $basename [OPTIONS] COMMAND

options:
  -h, --help       This help information

commands:

  status   Status of the vpn systemd service
  log      Display the systemd log from today
  start    Start $vpnservice
  stop     Stop $vpnservice
  restart  Restart $vpnservice
  help     This help information, same as using -h, --help

This script looks for the environment variable VPNCTL_SERVICE containing which
service to start/stop/restart. A value like this should be set

      VPNCTL_SERVICE="wg-quick@WIREGUARD_CONF.service"
      VPNCTL_SERVICE="openvpn-client@OPENVPN_CONF.service"

where WIREGUARD_CONF or OPENVPN_CONF are config files in /etc minus the .conf
extension.

log is performing this command:

  journalctl -u $vpnservice --since today

If you are seeing failures, this may help to explore them

  journalctl -u $vpnservice -S today | grep -B1 FAILURE

v1.3  2025-03-31  Dino Morelli <dino@ui3.info>

USAGE
)


warn () {
  echo "$basename:" "$@" >&2
}


die () {
  rc="$1"
  shift
  warn "$@"
  exit "$rc"
}


# arg parsing

getoptResults=$(getopt -o h --long help -n "$basename" -- "$@") \
  || die 1 "$usage"

# Note the quotes around "$getoptResults": they are essential!
eval set -- "$getoptResults"

optHelp=false

while true ; do
  case "$1" in
    -h|--help) optHelp=true; shift;;
    --) shift; break;;
  esac
done

$optHelp && die 0 "$usage"

if [ $# -ne 1 ]
then
  warn "COMMAND should be exactly one argument"
  die 1 "$usage"
fi

command=$1
shift

if [ -z "$vpnservice" ]
then
  warn "ERROR Can't continue because VPNCTL_SERVICE variable isn't set"
  die 1 "$usage"
fi

case "$command" in
  status)  set -x ; systemctl --no-pager status "$vpnservice" ;;
  log)     set -x ; journalctl -u "$vpnservice" --since today ;;
  start)   set -x ; sudo systemctl start "$vpnservice" ;;
  stop)    set -x ; sudo systemctl stop  "$vpnservice" ;;
  restart) set -x ; sudo systemctl restart "$vpnservice" ;;
  help)    die 0 "$usage";;
  *)
    warn "Invalid command: $command"
    die 1 "$usage";;
esac
