#! /bin/sh

#--------------------------------------------------------------------------
# $HeadURL$
#--------------------------------------------------------------------------
# $Revision$
# $Date$
# $Author$
#
# Determine some specifics about the machine's physical location at boot
# Store this information in a file
#--------------------------------------------------------------------------


vUsbDevs=/proc/bus/usb/devices
vLocCheckFile=/var/tmp/locCheck


echo -n "Attempting to autodetect docking status...  "

# XXX This code here really sucks, make it a loop
# This is the keyboard at home
#vLocation=`grep "Microsoft Internet Keyboard Pro" $vUsbDevs`
# This is the new KVM switch, the keyboard is obscured by it.
vLocation=`grep "Justcom Technology" $vUsbDevs`
if [ "$vLocation" = "" ]
then
    # This is the keyboard at work at SCK
    #vLocation=`grep "USBPS2" $vUsbDevs`

    # This is the USB to PS/2 adapter for the keyboard at NetApp
    vLocation=`grep "CHESEN" $vUsbDevs`
fi

if [ "$vLocation" = "" ]
then
    vProfile="laptop"
else
    vProfile="docked"
fi
echo "$vProfile"


echo -n "Attempting to autodetect USB mouse presence...  "

vMouse=`grep "S:.*Manufacturer=Kensington" $vUsbDevs`

if [ "$vMouse" = "" ]
then
    vMouse=0
    echo "NO MOUSE DETECTED"
else
    vMouse=1
    echo "Mouse is present"
fi


# Write results into the file
echo "lcLocation=$vProfile" > $vLocCheckFile
echo "lcMouseDetected=$vMouse" >> $vLocCheckFile
