#! /bin/bash

sessionname=${1?Must supply a screen sessionname}
cmdFile=${2?Must supply a command file specifier}

# This is an example, will only work in this dir.
# Should be something like $HOME/.screen
screenCmdDir="."

screen -S $sessionname -c ${screenCmdDir}/${cmdFile}.screen
