#! /bin/bash

${1?Must supply a screen sessionname}
${2?Must supply a command file specifier}

# This is an example, will only work in this dir.
# Should be something like $HOME/.screen
screenCmdDir="."

screen -S $1 -c ${screenCmdDir}/${2}.screen
