#! /usr/bin/perl -w

#--------------------------------------------------------------------------
# $HeadURL$
#--------------------------------------------------------------------------
# $Revision: 123 $
# $Date: 2005-09-12 10:40:16 -0400 (Mon, 12 Sep 2005) $
# $Author: dmorelli $
#
# Rename files with a regular expression
#--------------------------------------------------------------------------

use MIME::Base64;

$plain = shift @ARGV;
printf ("%s", encode_base64(eval "\"$plain\""));

