#! /usr/bin/perl -w

#--------------------------------------------------------------------------
# $RCSfile$
#--------------------------------------------------------------------------
# $Revision: 10 $
# $Date: 2004-03-18 16:51:33 -0500 (Thu, 18 Mar 2004) $
# $Author: dmorelli $
#
# Rename files with a regular expression
#--------------------------------------------------------------------------

use MIME::Base64;

$plain = shift @ARGV;
printf ("%s", encode_base64(eval "\"$plain\""));

