#! /usr/bin/perl -w

#--------------------------------------------------------------------------
# $HeadURL: file:///var/lib/svn/scripts/trunk/b64enc $
#--------------------------------------------------------------------------
# $Revision: 156 $
# $Date: 2005-09-12 14:00:39 -0400 (Mon, 12 Sep 2005) $
# $Author: dmorelli $
#
# Rename files with a regular expression
#--------------------------------------------------------------------------

use MIME::Base64;

$plain = shift @ARGV;
printf ("%s", encode_base64(eval "\"$plain\""));

