#! /bin/sh

#--------------------------------------------------------------------------
# $RCSfile$
#--------------------------------------------------------------------------
# $Revision: 71 $
# $Date: 2005-03-14 21:16:58 -0500 (Mon, 14 Mar 2005) $
# $Author: dmorelli $
#
# Script to quickly check the contents of the inserted CD and then
# umount it.
#--------------------------------------------------------------------------

# Script to quickly display back the root dir of the CD in the 
# drive and then umount it.

CDDIR=/mnt/cdrom/

mount $CDDIR
ls -lh $CDDIR
umount $CDDIR

