#! /bin/sh

#--------------------------------------------------------------------------
# $HeadURL: file:///var/lib/svn/scripts/trunk/dos2unix $
#--------------------------------------------------------------------------
# $Revision: 156 $
# $Date: 2005-09-12 14:00:39 -0400 (Mon, 12 Sep 2005) $
# $Author: dmorelli $
#
# Script to fix the line ending of a DOS style file to be like Unix
#--------------------------------------------------------------------------

newfile=$1
oldfile=$1.old

#echo $newfile
#echo $oldfile

mv $newfile $oldfile

sed -e 's/
//' $oldfile > $newfile

if [ -e $newfile ]
then
	rm $oldfile
fi

