#! /bin/sh

#--------------------------------------------------------------------------
# $RCSfile$
#--------------------------------------------------------------------------
# $Revision: 2 $
# $Date: 2004-02-25 12:53:24 -0500 (Wed, 25 Feb 2004) $
# $Author: dmorelli $
#
# Script to fix the line ending of a DOS style file to be like Unix
#--------------------------------------------------------------------------

newfile=$1
oldfile=$1.old

#echo $newfile
#echo $oldfile

mv $newfile $oldfile

sed -e 's/
//' $oldfile > $newfile

if [ -e $newfile ]
then
	rm $oldfile
fi

