#! /usr/bin/perl

#--------------------------------------------------------------------------
# $RCSfile$
#--------------------------------------------------------------------------
# $Revision: 2 $
# $Date: 2004-02-25 12:53:24 -0500 (Wed, 25 Feb 2004) $
# $Author: dmorelli $
#
# This script fixes a file that has double blank lines because of some 
# kind of line-ending mangling.
# Started on 2001-Jul-27
#--------------------------------------------------------------------------

use File::Copy;

# Define what a blank line means exactly.
$blankline = "\r\n";
#$blankline = "\n\n";

# Construct filenames.
$newfile = $ARGV[0];
$oldfile = "${newfile}_bu";

# Rename the original file to the backup (old) name.
# We'll be writing to a file with the original name and leaving that one.
move($newfile, $oldfile);

# Open them both.
open(OLDFILE, "<", $oldfile);
open(NEWFILE, ">", $newfile);

# Loop through each line, sending the appropriate ones to the new file.
while ($line = <OLDFILE>)
{
	# If this is a blank line, skip it but _do_ print the next one.
	# This preserves blanks that were in the file on purpose originally.
	if ($line eq $blankline)
	{ $line = <OLDFILE>; }

	print NEWFILE $line;
}  # while

# Close the files.
close($NEWFILE);
close($OLDFILE);

# Delete the backup original.
unlink($oldfile);

