#! /usr/bin/perl -w

#--------------------------------------------------------------------------
# $RCSfile$
#--------------------------------------------------------------------------
# $Revision: 26 $
# $Date: 2004-06-27 17:07:28 -0400 (Sun, 27 Jun 2004) $
# $Author: dmorelli $
#
# MP3 name fixer, uses rren
#--------------------------------------------------------------------------

use Getopt::Std;


#--------------------------------------------------------------------------
sub displayUsage()
{
	print "$0 - Fix music filenames (no spaces, etc)\n";
	print "version 1.0.0  Dino Morelli  dmorelli\@reactorweb.net\n";
	print "\nusage:\n";
	print "   $0 [-n] files...\n";
	print "   $0 --help\n";
	print "   $0 --version\n";
	print "\nswitches:\n";
	print "   -n         No execution mode. AKA dry run.\n";
	print "   --help     This information.\n";
	print "   --version  This information.\n";

	exit;
}  # sub displayUsage


#--------------------------------------------------------------------------
# Detect if no params given.
if(@ARGV == 0 || $ARGV[0] eq "--help" || $ARGV[0] eq "--version")
{ displayUsage(); }

# Parse arguments.
$opt_n = 0;
getopts("-n");

if($opt_n == 1) { $dryRun = "-n"; }
else { $dryRun = ""; }

# Loop through the files given, wrapping each one with double quotes.
for $current (@ARGV)
{
	push @files, "\"$current\"";
}

$expression = 's/\(The\) //g;s/(.*), (.*) (-) (.*)/\$2\$1\$3\$4/g;s/[,\'#]//g;s/[ )](.)/\U\$1/g;s/[(](.)/\U\$1/g';
print qx|rren $dryRun \"$expression\" @files|;
