#!/bin/sh

#--------------------------------------------------------------------------
# $HeadURL: file:///var/lib/svn/scripts/trunk/ntpdatewrap $
#--------------------------------------------------------------------------
# $Revision: 113 $
# $Date: 2005-09-12 09:47:56 -0400 (Mon, 12 Sep 2005) $
# $Author: dmorelli $
#
# ntpdate cron nightly, this is from:
# http://www.debian.org/doc/manuals/system-administrator/ch-sysadmin-time.html
#--------------------------------------------------------------------------


NTPDATE=/usr/sbin/ntpdate
LOGFILE=/var/log/ntpdatewrap
NTPCONFFILE=/etc/ntp.conf
NTPSERVERS=
GREP=/usr/bin/grep
CUT=/usr/bin/cut

if [ -f $NTPCONFFILE ] ; then
    echo "===========================" >> $LOGFILE
    echo "<<< `date` " >> $LOGFILE
    for i in `grep ^server $NTPCONFFILE | $CUT --fields 2 --delimiter \ `
    do
        NTPSERVERS="$NTPSERVERS $i"
    done
    $NTPDATE $NTPSERVERS  >>  $LOGFILE
    ###echo $NTPDATE $NTPSERVERS $LOGFILE
    echo ">>> `date` " >> $LOGFILE
fi

exit 0
