#! /bin/sh

#--------------------------------------------------------------------------
# $RCSfile$
#--------------------------------------------------------------------------
# $Revision: 38 $
# $Date: 2004-07-12 00:51:41 -0400 (Mon, 12 Jul 2004) $
# $Author: dmorelli $
#
# Script to do some common tasks with Palm PDAs
#--------------------------------------------------------------------------


SYNCFOLDER=~/.palmpda

waitForDevice()
{
	echo Waiting for PDA...
	sleep 7s

	echo Connecting now...
}

displayUsage()
{
	echo "Perform Palm PDA operations"
	echo "usage:"
	echo "  palm -i file1 file2 ...   Install files"
	echo "  palm -s                   Sync the PDA"
	echo "  palm --help               This help information."

	exit
}

# It all starts here

# No args or user requested help
if [ "$#" -lt "1" -o "$1" == "--help" ]
then displayUsage; fi

# Parse arguments
while getopts "is" opt
do
	if [ ! "$action" == "" ]
	then
		echo "Only one action must be chosen"
		displayUsage
	fi
	action=$opt
done

# Perform action
case $action in
	i)
		waitForDevice

		shift
		pilot-xfer -i $@
		break;;

	s)
		waitForDevice

		pilot-xfer -s ${SYNCFOLDER}
		break;;
esac
echo Done
