#! /bin/sh

#--------------------------------------------------------------------------
# $RCSfile$
#--------------------------------------------------------------------------
# $Revision: 81 $
# $Date: 2005-04-12 22:21:34 -0400 (Tue, 12 Apr 2005) $
# $Author: dmorelli $
#
# Script to do some common tasks with Palm PDAs
#--------------------------------------------------------------------------


SYNCFOLDER=~/.palmpda
USAGE=`cat <<EOF
Perform Palm PDA operations
usage:
  palm -i file1 file2 ...   Install files
  palm -s                   Sync the PDA
  palm --help               This help information.
EOF`

waitForDevice()
{
	echo Waiting for PDA...
	sleep 3s

	echo Connecting now...
}

displayUsage()
{
	echo "$USAGE"
	exit
}

# It all starts here

# No args or user requested help
if [ "$#" -lt "1" -o "$1" == "--help" ]
then displayUsage; fi

# Parse arguments
while getopts "is" opt
do
	if [ ! "$action" == "" ]
	then
		echo "Only one action must be chosen"
		displayUsage
	fi
	action=$opt
done

# Perform action
case $action in
	i)
		waitForDevice

		shift
		pilot-xfer -i "$@"
		break;;

	s)
		waitForDevice

		pilot-xfer -s ${SYNCFOLDER}
		break;;
esac
echo Done
