#! /bin/sh

#--------------------------------------------------------------------------
# $HeadURL: file:///var/lib/svn/scripts/trunk/perlsearch $
#--------------------------------------------------------------------------
# $Revision: 156 $
# $Date: 2005-09-12 14:00:39 -0400 (Mon, 12 Sep 2005) $
# $Author: dmorelli $
#
# Search through locally installed Perl POD documentation with grep
#--------------------------------------------------------------------------

# Set a PERLPOD environment variable. Try to locate where your system
# puts the pod files like this:
#
# find / -regex ".*\.pod" | less
#
# Then, in something like your ~/.bash_profile or whatever do:
#
# PERLPOD="/dir/found/above"
# export PERLPOD

find $PERLPOD -regex ".*\.pod" | xargs grep "$1"
