#! /bin/sh

#--------------------------------------------------------------------------
# $RCSfile$
#--------------------------------------------------------------------------
# $Revision: 35 $
# $Date: 2004-07-08 11:54:24 -0400 (Thu, 08 Jul 2004) $
# $Author: dmorelli $
#
# Search through locally installed Perl POD documentation with grep
#--------------------------------------------------------------------------

# Set a PERLPOD environment variable. Try to locate where your system
# puts the pod files like this:
#
# find / -regex ".*\.pod" | less
#
# Then, in something like your ~/.bash_profile or whatever do:
#
# PERLPOD="/dir/found/above"
# export PERLPOD

find $PERLPOD -regex ".*\.pod" | xargs grep "$1"
