#! /usr/bin/perl -w

#--------------------------------------------------------------------------
# $HeadURL: file:///var/lib/svn/scripts/trunk/rren $
#--------------------------------------------------------------------------
# $Revision: 156 $
# $Date: 2005-09-12 14:00:39 -0400 (Mon, 12 Sep 2005) $
# $Author: dmorelli $
#
# Rename files with a regular expression
#--------------------------------------------------------------------------

use File::Copy;
use Getopt::Std;


#--------------------------------------------------------------------------
sub displayUsage()
{
	print "$0 - Rename files with a regular expression\n";
	print "version 1.0.0  Dino Morelli  dmorelli\@reactorweb.net\n";
	print "\nusage:\n";
	print "   $0 [-n] \'expression\' files...\n";
	print "   $0 --help\n";
	print "   $0 --version\n";
	print "\nswitches:\n";
	print "   -n         No execution mode. AKA dry run.\n";
	print "   --help     This information.\n";
	print "   --version  This information.\n";
	print "\nexamples:\n";
	print "   $0 \'s/[ -](.)/\\U\\1/g\' file1 file2\n";
	print "      Remove spaces and hyphens, upcase the char after.\n";
	print "   $0 -n \'s/,//g;s/z/X/\' file*\n";
	print "      Remove all commas. Change first z to an X.\n";
}  # sub displayUsage


#--------------------------------------------------------------------------
sub changeName($)
{
	my $oldfile = shift;
	$_ = $oldfile;
	eval $re;
	my $newfile = $_;

	# Same name, no change needed.
	if($oldfile eq $newfile)
	{
		print "No change needed for $oldfile\n";
		return;
	}

	# Check for file already exists. DO NOT OVERWRITE.
	if(-e $newfile)
	{
		print "File $newfile already exists! Aborting!\n";
		return;
	}

	# Only do the move if not in dry run mode.
	if($opt_n == 0) { move($oldfile, $newfile); }

	print "\"$oldfile\" -> $newfile\n";
}  # sub rename


#--------------------------------------------------------------------------
# Detect if no params given.
if(@ARGV == 0 || $ARGV[0] eq "--help" || $ARGV[0] eq "--version")
{
	displayUsage();
	exit;
}

# Parse arguments.
$opt_n = 0;
getopts("-n");
$re = shift;

if($opt_n == 1) { print "*No execution mode*\n"; }

# Loop through the files given and do the change.
for $current (@ARGV) { changeName($current); }

