#! /usr/bin/perl -w

#--------------------------------------------------------------------------
# $RCSfile$
#--------------------------------------------------------------------------
# $Revision: 87 $
# $Date: 2005-06-17 17:14:56 -0400 (Fri, 17 Jun 2005) $
# $Author: dmorelli $
#
# Convert seconds into MM:SS notation
#--------------------------------------------------------------------------

use strict;
use POSIX qw(floor);


my $dec = shift() / 60;
my $m = floor $dec;
my $s = ($dec - $m) * 60;
printf "%02i:%02i\n", $m, $s;
