#! /usr/bin/perl -w

#--------------------------------------------------------------------------
# $HeadURL$
#--------------------------------------------------------------------------
# $Revision: 150 $
# $Date: 2005-09-12 10:40:43 -0400 (Mon, 12 Sep 2005) $
# $Author: dmorelli $
#
# Convert seconds into MM:SS notation
#--------------------------------------------------------------------------

use strict;
use POSIX qw(floor);


my $dec = shift() / 60;
my $m = floor $dec;
my $s = ($dec - $m) * 60;
printf "%02i:%02i\n", $m, $s;
