#! /usr/bin/perl -w

#--------------------------------------------------------------------------
# $HeadURL: file:///var/lib/svn/scripts/trunk/spamTally $
#--------------------------------------------------------------------------
# $Revision: 156 $
# $Date: 2005-09-12 14:00:39 -0400 (Mon, 12 Sep 2005) $
# $Author: dmorelli $
#
# Calculates some statistics on spam emails.
#--------------------------------------------------------------------------

$mailPath = shift;

open MAILFILE, "<$mailPath" or die "Can't open file $mailPath: $!\n";

$total = 0.0;
$count = 0;
$min = 6.5;
$max = 0;
while (<MAILFILE>)
{
	/^X-Spam-Status: Yes, hits=([^ ]*) .*/ && do
	{
		#print "item: $1\n";
		$total += $1;
		$count++;
		if ($1 < $min) { $min = $1; }
		if ($1 > $max) { $max = $1; }
	}
}

close MAILFILE;

if($count < 1)
{
	$min = 0.0;
	$average = "n/a";
}
else
{
	$average = $total / $count;
}

print "mbox:    $mailPath\n";
print "count:   $count\n";
print "min:     $min\n";
print "max      $max\n";
print "average: $average\n";

