#!/bin/sh

#--------------------------------------------------------------------------
# $RCSfile$
#--------------------------------------------------------------------------
# $Revision: 85 $
# $Date: 2005-05-14 00:30:41 -0400 (Sat, 14 May 2005) $
# $Author: dmorelli $
#
# Script as detailed by man growisofs to allow burning with sudo
#--------------------------------------------------------------------------

unset SUDO_COMMAND
export MKISOFS=/usr/bin/mkisofs
exec growisofs "$@"
