#!/bin/sh

#--------------------------------------------------------------------------
# $HeadURL$
#--------------------------------------------------------------------------
# $Revision: 126 $
# $Date: 2005-09-12 10:40:19 -0400 (Mon, 12 Sep 2005) $
# $Author: dmorelli $
#
# Script as detailed by man growisofs to allow burning with sudo
#--------------------------------------------------------------------------

unset SUDO_COMMAND
export MKISOFS=/usr/bin/mkisofs
exec growisofs "$@"
