#! /bin/sh

#--------------------------------------------------------------------------
# $RCSfile$
#--------------------------------------------------------------------------
# $Revision: 70 $
# $Date: 2005-03-14 15:47:44 -0500 (Mon, 14 Mar 2005) $
# $Author: dmorelli $
#
# Script to start XFree86 with a certain layout.
#--------------------------------------------------------------------------

displayHelp () {
	echo "`basename $0` - start XFree86 with a specific layout"
   echo "  Program will attempt to detect docked status"
	echo ""
	echo "usage:"
	echo "  xgo [laptop|docked]"
	echo "  xgo --help"
}

PROFILE=$1

if [ "$PROFILE" = "" ]
then
	USBDEVS="/proc/bus/usb/devices"

	# This is the keyboard at home
	DOCKED=`grep "Microsoft Internet Keyboard Pro" $USBDEVS`
	if [ "$DOCKED" = "" ]
	then
		# This is the keyboard at work at SCK
		DOCKED=`grep "USBPS2" $USBDEVS`
	fi

	if [ "$DOCKED" = "" ]
	then
		echo "Machine detected to be NOT docked"
		PROFILE="laptop"
	else
		echo "Machine detected to be docked"
		PROFILE="docked"
	fi

	# For debugging
	#exit 1
elif [ "$PROFILE" = "--help" ]
then
	displayHelp
	exit 1
fi

startx -- -layout $PROFILE
