#! /bin/sh

#--------------------------------------------------------------------------
# $HeadURL: file:///var/lib/svn/scripts/trunk/xslt $
#--------------------------------------------------------------------------
# $Revision: 156 $
# $Date: 2005-09-12 14:00:39 -0400 (Mon, 12 Sep 2005) $
# $Author: dmorelli $
#
# Script to perform an XSL transformation with xalan.
#--------------------------------------------------------------------------

java -jar ~/lib/java/xalan.jar $1 $2 $3 $4 $5 $6 $7 $8 $9

