#! /bin/sh

#--------------------------------------------------------------------------
# $HeadURL: file:///var/lib/svn/scripts/trunk/spamLearn/spamLearn $
#--------------------------------------------------------------------------
# $Revision: 156 $
# $Date: 2005-09-12 14:00:39 -0400 (Mon, 12 Sep 2005) $
# $Author: dmorelli $
#
# Script to train SpamAssassin from the supplied mbox file and then
# delete the messages.
#--------------------------------------------------------------------------

mailFolder=$1

# Train SpamAssassin with the mail in the supplied folder
#sa-learn --spam --mbox --no-rebuild $mailFolder
sa-learn --spam --mbox $mailFolder


# Remove the spam from the folder

mailFolderNew=${mailFolder}.new

awk '/^From / { messages++ }; messages > 1 { exit 0 }; { print }' $mailFolder > $mailFolderNew

if [ -e $mailFolderNew ]
then
	rm $mailFolder
	mv $mailFolderNew $mailFolder
fi
