#! /usr/bin/perl -w

#--------------------------------------------------------------------------
# Set up email log viewer for fetchmail and procmail
#--------------------------------------------------------------------------

use strict;
use FindBin qw($RealBin);


my $title = 'maillogs';
my $confFile = $RealBin . '/maillogs.screen';

exec "Eterm -g80x43 -T $title -n $title -e screen -S $title -c $confFile &";
