#! /usr/bin/perl -w

#--------------------------------------------------------------------------
# $HeadURL$
#--------------------------------------------------------------------------
# $Revision: 120 $
# $Date: 2005-09-12 10:40:13 -0400 (Mon, 12 Sep 2005) $
# $Author: dmorelli $
#
# Set up email log viewer for fetchmail and procmail
#--------------------------------------------------------------------------

use strict;
use FindBin qw($RealBin);


my $title = 'maillogs';
my $confFile = $RealBin . '/maillogs.screen';

exec "Eterm -g80x43 -T $title -n $title -e screen -S $title -c $confFile &";
