#! /bin/sh

# A script to start the Second Life client on UNIX-like environments. It's
# expecting to see SL installed in /usr/local/share as with the related
# tool in this package: install-sl

# This script is intended to live somewhere on the PATH like /usr/local/bin

# Notice that it also sets the web browser that will be used from within
# Second Life


cd /usr/local/share/SecondLife
BROWSER=/usr/bin/iceweasel ./secondlife
